USE ClinicaDB
GO
-- IMPORTANTE: Desactiva restricciones si es necesario
ALTER TABLE Turnos NOCHECK CONSTRAINT ALL;
ALTER TABLE Jornadas NOCHECK CONSTRAINT ALL;
ALTER TABLE Usuario NOCHECK CONSTRAINT ALL;
ALTER TABLE Medico NOCHECK CONSTRAINT ALL;
ALTER TABLE Paciente NOCHECK CONSTRAINT ALL;
ALTER TABLE Correos NOCHECK CONSTRAINT ALL;
ALTER TABLE Telefonos NOCHECK CONSTRAINT ALL;
ALTER TABLE Persona NOCHECK CONSTRAINT ALL;

-- Borrado en orden inverso al de dependencias
DELETE FROM Turnos;
DELETE FROM Jornadas;
DELETE FROM Usuario;
DELETE FROM Medico;
DELETE FROM Paciente;
DELETE FROM Correos;
DELETE FROM Telefonos;
DELETE FROM Persona;

-- Luego las tablas maestras
DELETE FROM Localidades;
DELETE FROM Provincias;
DELETE FROM Paises;
DELETE FROM Especialidades;
DELETE FROM ObraSocial;
DELETE FROM EstadoTurnos;
DELETE FROM Roles;
DELETE FROM Sexos;

-- Reactivar restricciones
ALTER TABLE Turnos CHECK CONSTRAINT ALL;
ALTER TABLE Jornadas CHECK CONSTRAINT ALL;
ALTER TABLE Usuario CHECK CONSTRAINT ALL;
ALTER TABLE Medico CHECK CONSTRAINT ALL;
ALTER TABLE Paciente CHECK CONSTRAINT ALL;
ALTER TABLE Correos CHECK CONSTRAINT ALL;
ALTER TABLE Telefonos CHECK CONSTRAINT ALL;
ALTER TABLE Persona CHECK CONSTRAINT ALL;
